[build]
  base = "addressbook"
  command = "npm run build"
  publish = "addressbook/dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://69885ba2780e8375a6881c24.mockapi.io/users"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
